[package]
name = "vecnn"
version = { workspace = true }
edition = "2021"


[features]
default = ["tracking"]
tracking = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
heapless = "0.8.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
